### ISSUE TITLE
Add user setting to set shortcuts or collections as default landing page

### ISSUE THREAD

**Issue by apricot13** [yourselfhosted/slash#102]
### Is your feature request related to a problem?

When I login I have to switch to the collections view everytime

### Describe the solution you'd like

I would like a setting in my profile to set my default 'homepage' to be either shortcuts or collections

### Additional context

I'm mostly using slash as a way to manage curated collections of links, like the awesome-* lists only much smaller or for links relating to my current projects. It's not a huge issue to switch to collections manually but I figured other people might be focusing primarily on curating links too and might want to save a click!

**Comment by boojack** [comment]
Great idea, but we think it might be better to avoid adding a setting by caching the last visit page (`/shortcuts` or `/collections`). A simple version of this was implemented with https://github.com/yourselfhosted/slash/commit/70602b8c6c695232d1c7df3f64e78ce94d4fef11 and you can experience it by updating the docker image.
