### ISSUE TITLE
Add support for other databases

### ISSUE THREAD

**Issue by micash545** [yourselfhosted/slash#145]
### Is your feature request related to a problem?

Improve performance

### Describe the solution you'd like

Add support for mariadb and postgresql

**Comment by boojack** [comment]
We've supported PostgreSQL, FYI.

```
docker run -d --name slash -p 5231:5231 -v ~/.slash/:/var/opt/slash yourselfhosted/slash:latest --driver postgres --dsn 'postgresql://postgres:PASSWORD@localhost:5432/slash'
```
