### ISSUE TITLE
More informations about the users flow

### ISSUE THREAD

**Issue by aminnairi** [yourselfhosted/slash#156]
### Is your feature request related to a problem?

It is not clear whether the first user is an administrator, and I had to blindly register to understand that it was indeed the first user that has the administrator privileges.

### Describe the solution you'd like

Clearly state in the documentation that the first user is an administrator, and that it can disable registration to only allow trusted users to login to the app by adding them manually.

### Additional context

I'm self-hosting this app using Docker.

**Comment by boojack** [comment]
Updated with https://github.com/yourselfhosted/slash/commit/769b474bdcb309ba78bec28f48b69e4fd03f3edf. When there is no user, it will always redirect the `/signup` and show a prompt that it is currently registering as an administrator.

<img width="495" alt="image" src="https://github.com/yourselfhosted/slash/assets/24653555/54ba7f12-a5eb-483e-b87c-dba85ef65302">
