### ISSUE TITLE
Option to disable account registration not found

### ISSUE THREAD

**Issue by TheKing6488** [yourselfhosted/slash#275]
### Describe the bug

Option to disable account registration not found.

### Steps to reproduce

![grafik](https://github.com/user-attachments/assets/a7c50e91-540e-4ca3-bfc6-4917b945731a)

### Expected behavior

A slightly older post there was still this function
https://github.com/yourselfhosted/slash/issues/14

### Screenshots or additional context

**Comment by boojack** [comment]
Thanks for your report. Please update to the latest `v1.0.0`, the setting item will be in the `setting` -> `security section`.

<img width="840" alt="image" src="https://github.com/user-attachments/assets/8b3d26e7-33cb-406d-b787-4fe28b609b19">

**Comment by TheKing6488** [comment]
Thanks for the quick solution and the good description to find the function. 
You have created a really cool app.

**Comment by YellowTech** [comment]
I just noticed that the text "Disallow user registration" is not affected by the theme settings, so the font stays dark on dark mode:
<img width="1370" alt="grafik" src="https://github.com/user-attachments/assets/2f0170b8-cfa3-43c5-b9c4-d300a1905ea5">

<img width="1013" alt="grafik" src="https://github.com/user-attachments/assets/aa01fec9-ba4f-4009-912f-5ac7911ee6ce">

**Comment by boojack** [comment]
@YellowTech Good catch, fixed with https://github.com/yourselfhosted/slash/commit/f11a295ac211aed1f273d712a3c767a10d0ed7a8
