### ISSUE TITLE
Browser extension and docs mismatched

### ISSUE THREAD

**Issue by BaccanoMob** [yourselfhosted/slash#298]
### Describe the bug

Features listed in or seen in the screenshots of [the docs](https://github.com/yourselfhosted/slash/blob/main/docs/install-browser-extension.md) are not seen in the web extension when installed from store. I do not know if the docs is out of date or if the extension itself is.

### Steps to reproduce

1. Install the web extension from the web store ( [chrome](https://chrome.google.com/webstore/detail/slash/ebaiehmkammnacjadffpicipfckgeobg) or [firefox](https://addons.mozilla.org/firefox/addon/your-slash/))
2. Click the slash in the extensions bar > settings
3. Access token will be missing in the settings (and Domain is renamed as Instance url)
4. List of extensions is not seen afterwards (even if the shortcuts listed as public)

### Expected behavior

Access token will help bypass the logging in process even in incognito or if I clear cookies/history in my browser. This feature is missing in the web extension release unlike mentioned in the docs.

**Comment by boojack** [comment]
Thanks for your report. The extension docs has been updated with https://github.com/yourselfhosted/slash/commit/ba62afc03400eff2e394397bc78ef9eced0a8b7a. 

Now the extension only needs the instance URL of your Slash. The principle is to redirect `s/xxx` to `instance-url/s/xxx`, making it more concise.
