### ISSUE TITLE
Usage as internal link manager for company

### ISSUE THREAD

**Issue by heynemann** [yourselfhosted/slash#50]
### Is your feature request related to a problem?

slash is GREAT! I just have a few minor requests that may be added as configuration that would make it even better for my use case.

1. We want users to provide a memorable name for urls all the time. No use for the auto-generated url since the goal is not to share outside the company. This will be used in the VPN.
2. We want this tool to be as lean as possible for our users, so the less they have to fill the better. Ideally they'd fill the URL and memorable name. That's it.

### Describe the solution you'd like

1. Would it be possible to have a config (flag? env var?) that changes the UI behavior from defaulting to auto-generated to defaulting to an empty input? That would be enough for our use case.
2. I think there's a two phase approach here:
a. First we can have a config just to disable the title being required. That is already good enough for us since we don't really care about the title or the other metadata.
b. Second I think a good addition to slash would be to query the URL provided for the link and get the metadata from the page and automatically fill the metadata for me (og:title, og:description and such). That would be amazing! 

### Additional context

We are adopting slash as our internal go links tool and these changes would make it easier on our end. Thanks so much for the amazing work!

**Comment by dashrandom** [comment]
@heynemann no need for customization on Slash to do this at all.

What you need to do is to make use of the address bar search engine function in most modern browsers.

Add a search engine with "http://s/%s" in the query URL, then make this search engine the default search engine. It will basically add "s/" in front of whatever is typed into the URL bar after. Only downside is that the same prefix will be added regardless of the search query the user types, unless there is some way to have a fallback search engine.

![image](https://github.com/yourselfhosted/slash/assets/9287237/a4560d5f-11ce-4c41-a43b-944ff0620e29)

**Comment by dashrandom** [comment]
Of course the problem will then be how to deploy this to all your colleagues in your company... If everyone was using Windows, you could probably push this via GroupPolicy or a bat file but I'm not sure how it'd work across different OSes / browsers...

**Comment by heynemann** [comment]
Sorry I don't understand how that solves the problems I listed above... Maybe this is meant to be an answer for the other issue I created?

**Comment by dashrandom** [comment]
@heynemann sorry maybe I misunderstood your request. I interpreted it as not needing to have the "s/" in order to use a shortcut? At least the first part of your request.

**Comment by heynemann** [comment]
Not at all :) The `s/` can easily be fixed with reverse proxying. I want users to be required to provide a memorable name like `my-url` instead of using the auto-generated `a82ef2`, since the auto-generated one is useless for internal links (as people won't remember that).

**Comment by boojack** [comment]
Already released in the `v0.5.1`.

<img width="402" alt="image" src="https://github.com/yourselfhosted/slash/assets/24653555/031dabb8-54c3-4fdc-8121-9f9027865914">

**Comment by heynemann** [comment]
Awesome!!!

Bernardo Heynemann
