### ISSUE TITLE
Extension unable to traverse Reverse proxy to Slash selfhosted instance 

### ISSUE THREAD

**Issue by dashrandom** [yourselfhosted/slash#52]
### Describe the bug

- Extension is unable to pull saved shortcuts from selfhosted instance
- Refreshing the shortcuts does not work

### Steps to reproduce

1. Deploy Slash through docker and use a reverse proxy (traefik in my case) to route 443 HTTPS to container port
2. Download and install extension
3. Enter hostname into Slash Extension
4. No shortcuts are pulled, refresh also does not pull any shortcuts

### Expected behavior

Shortcuts are pulled to Slash Extension

### Workaround discovered 

1. Only when keying in ":443" at the end of hostname are shortcuts pulled
2. No problem pulling shortcuts from then onwards, even after changing hostname back without ":443"

**Comment by dashrandom** [comment]
I apologise, please ignore the workaround, it seems that the problem has reoccurred and my proposed workaround does not work.

I am not sure if this is a result of using Cloudflare as a proxy on the frontend. Looking at the console on the extension settings page after pressing the sync button shows this.

![2023-12-22 13_28_34-ARMOURY CRATE](https://github.com/yourselfhosted/slash/assets/9287237/fd650fa7-e4ed-48a7-ada2-5574aca9e070)

**Comment by boojack** [comment]
@dashrandom Ideally it should look something like the following. You can send out the network request error.

https://github.com/yourselfhosted/slash/assets/24653555/4dad488e-a297-474c-b143-cc62ceb264bc

**Comment by dashrandom** [comment]
@boojack even stranger thing is that I'm getting the right responses but the extension isn't updating them. Take a look at the screenshot where there is an id 25 but only 17 shortcuts. Let me know what other logs I can provide.

![2023-12-22 13_58_48-Slash and 20 more pages - Personal - Microsoft​ Edge](https://github.com/yourselfhosted/slash/assets/9287237/60d33bf8-be49-4088-9e0d-19754ea1473a)

**Comment by boojack** [comment]
So you are able to synchronize normally. The response length is not related with the max id. Maybe another user created some private shortcuts or you deleted before.

**Comment by dashrandom** [comment]
@boojack I'm really not able to synchronize normally. The response is received normally but the extension doesn't update.

Yes, I'm aware of the possibility of the ids not matching the number of shortcuts as the database will simply increment the id but this is a single user instance and I've not deleted any shortcuts.

What do I have to provide to show you that the number of shortcuts on the web instance and the number of shortcuts on the extension are not the same? There are clearly missing shortcuts, 25 on my instance vs 17 on the extension. Perhaps this screenshot will do?

![image](https://github.com/yourselfhosted/slash/assets/9287237/78589094-b9aa-4fd0-bb8f-fb1869714927)

**Comment by boojack** [comment]
It looks like it's because the browser storage limit was exceeded, I'll update the plugin in this weekend. You can upgrade the browser extension later.

https://stackoverflow.com/a/50420638

**Comment by boojack** [comment]
A new extension version `v1.0.3` have been submitted to the chrome extension store.
