### ISSUE TITLE
Option to disable metrics?

### ISSUE THREAD

**Issue by krohrsb** [yourselfhosted/slash#54]
### Is your feature request related to a problem?

Not really a problem, other than I personally don't need metrics sent out from my selfhosted instance.

### Describe the solution you'd like

I'd like to see a configuration option to disable metrics so that when Slash is self-hosted, it doesn't call out in this manner.

### Additional context

I notice various calls to `https://app.posthog.com/batch/` from the instance, which on my network are blocked (due to network policies). So was wondering if it would be a good idea to simply allow one to opt-out.

**Comment by boojack** [comment]
Updated in https://github.com/yourselfhosted/slash/commit/2771602e5c31b0f9bc72b74206fcccd2966da47f
