### ISSUE TITLE
Extension: Auto populate or do not require "name"

### ISSUE THREAD

**Issue by krohrsb** [yourselfhosted/slash#55]
### Is your feature request related to a problem?

Its a usability question regarding the browser extension.

### Describe the solution you'd like

I'd like to make adding bookmarks as quick as possible. Requiring me to manually fill out a "name" when adding one is a bit troublesome. I'd like to see this somehow be optional, or auto populated & editable. I'm not 100% sure what/where it is used from a technical perspective, but hopefully I've conveyed my ask well enough for one to determine if it is appropriate/doable or not.

**Comment by boojack** [comment]
Added a new button to generate random names.

<img width="526" alt="image" src="https://github.com/yourselfhosted/slash/assets/24653555/287ec063-bb3c-4da1-9253-a20d9482b9c7">
