### ISSUE TITLE
Healthcheck Support

### ISSUE THREAD

**Issue by heynemann** [yourselfhosted/slash#56]
### Is your feature request related to a problem?

Running slash in K8s requires a healthcheck route. While it is possible to just use `/` it would be great to have something like `/status` or `/health`. If that exists I was not able to find it.

### Describe the solution you'd like

Just a route that returns `OK` or something :) Could be a route that also queries Postgres to make sure everything is alright.

**Comment by boojack** [comment]
Updated with https://github.com/yourselfhosted/slash/commit/4bc2a0ff421bc180e23ee6887275a8bd08113024

**Comment by heynemann** [comment]
THANKS!!!
