### ISSUE TITLE
Default Behavior on 404

### ISSUE THREAD

**Issue by heynemann** [yourselfhosted/slash#59]
### Is your feature request related to a problem?

Whenever I want to create a new shortcut I have to type `s/slash` (my shortcut to slash itself), then click the Create button, then start filling the details. It would be a great experience if whenever I get a 404, it could drop me in the new shortcut form with the name I used in the shortcut filled in the link name already.

### Describe the solution you'd like

Let's say I type `s/my-404-link`, a link that does not exist yet in Slash. What I want is for Slash to take me directly to the create shortcut form and have `my-404-link` already pre-filled in the shortcut name input. That would make for an incredible UX!

**Comment by boojack** [comment]
Updated with https://github.com/yourselfhosted/slash/commit/95f15707962f73fd062d53d5f6455a26664ba00d

https://github.com/yourselfhosted/slash/assets/24653555/6459d7a6-9b4a-40fb-b128-58b9bf7fd99d
