### ISSUE TITLE
Link Slug name is Black in Dark Mode

### ISSUE THREAD

**Issue by mariushosting** [yourselfhosted/slash#60]
### Describe the bug

If you set Dark Mode, then add a link, if you add a slug, that slug is under a black color, almost impossible too see it.

### Steps to reproduce

STEP 22 here: https://mariushosting.com/how-to-install-slash-with-postgresql-on-your-synology-nas/

The title becomes black when you click the link on STEP 23.

### Expected behavior

It should be another color, not black.

**Comment by boojack** [comment]
Subtext will always be a little darker than the main title, this is by design.

<img width="342" alt="image" src="https://github.com/yourselfhosted/slash/assets/24653555/a9971fed-e23c-4a21-9e9e-e2a69e03eeb7">

**Comment by mariushosting** [comment]
> Subtext will always be a little darker than the main title, this is by design.
> 
> <img alt="image" width="342" src="https://private-user-images.githubusercontent.com/24653555/302637585-a9971fed-e23c-4a21-9e9e-e2a69e03eeb7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcyMjc2ODcsIm5iZiI6MTcwNzIyNzM4NywicGF0aCI6Ii8yNDY1MzU1NS8zMDI2Mzc1ODUtYTk5NzFmZWQtZTIzYy00YTIxLTllOWUtZTJhNjllMDNlZWI3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjA2VDEzNDk0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVjNTIyMmUzNjI0MGYwNmIzZWE1M2ZiYjcxYWMyZDViYWU2Zjc4OWE1NDM3ZmYzNTdjMmI5YmM5MDk5NmU1NDYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.fNHHcckNfy883BNtyyESTJjz66dB8K_jKVxP-pb4o2k">

@boojack Click the icon as per the example below. The text it's just Black.

![1](https://github.com/yourselfhosted/slash/assets/37554361/a40cb18a-ecc2-4780-b6a2-0bfa867a9ccf)
![2](https://github.com/yourselfhosted/slash/assets/37554361/776b670a-697b-460c-bb99-544f45407c77)
