### ISSUE TITLE
Max number of users

### ISSUE THREAD

**Issue by heynemann** [yourselfhosted/slash#61]
### Describe the bug

It won't allow more than 5 users to register and nowhere in the docs it says it is a paid product. It says explicitly it's an open source self-hosted product. What should I do?

### Steps to reproduce

Register more than 5 people.

### Expected behavior

Register the user, but instead we get a message saying that user limit has been reached.

### Screenshots or additional context

![image](https://github.com/yourselfhosted/slash/assets/60965/98401b9c-4965-4ba8-b3cd-1a436425a6b4)

**Comment by boojack** [comment]
> It won't allow more than 5 users to register and nowhere in the docs it says it is a paid product. It says explicitly it's an open source self-hosted product. What should I do?

Open source doesn't mean free. Opting for a paid plan not only unlocks enhanced features but also contributes to better service and long-term maintenance. The limitation on the number of users in the free version is in place to ensure the sustainability of our services. 

If you want to enable multi-user access for your team, you can purchase and add a Pro license by logging into `{your_instance_url}/setting/subscription` with administrator account. 

<img width="1140" alt="image" src="https://github.com/yourselfhosted/slash/assets/24653555/7df2df30-67a1-40de-8912-35c4e6f79ea2">

**Comment by heynemann** [comment]
I see, maybe it's a good idea to put that in the README as well...

**Comment by tarocjsu** [comment]
Really hate everything just asking $$$$$$$$$$$$
