### ISSUE TITLE
Ability to configure the default (initial) "Visibility" method when creating new Shortcuts

### ISSUE THREAD

**Issue by jon-f-novastor** [yourselfhosted/slash#62]
### Is your feature request related to a problem?

Add ability to configure the default (initial) "Visibility" method when creating new Shortcuts (to be able to override the hardcoded default mode, per Slash instance). It would be great if the instance owner (admin), could specify a flag saying what the default create new shortcut behavior should be, for the Visibility method, so that the default method can be predefined in either an .env file per Slash instance, or in a UI setting. In earlier versions the default (initial) "Visibility" method was "Private" and then starting in v0.5.2 the default (initial) mode was changed to "Public"; however that setting is not configurable by the instance owner/admin in v0.5.2 latest public release, and this request is to make it configurable.

### Describe the solution you'd like

At least (easiest to implement in the code) add an .env variable named something like "DEFAULT_URL_VISIBILITY" with private, workspace or public as allowed values. And once the instance is reloaded then use that as the default (initial) "Visibility" method for the entire instance for the "Create Shortcut" function in the UI. If there is extra time then add a global UI setting for the admin user to be able to change the default (initial) "Visibility" method, which would mean the .env flag is not needed or if it exists then one of those two settings would supercede (override) the other.

Note: I don't know if it would be worth having a configuration setting per user in the UI, like in the user's profile, but that could also be an idea for later. At least if a setting were enabled in the .env file, as a new variable flag, that would be easiest to implement by the instance owner in Linux, one time, instance wide.

### Additional context

![Screenshot_20240131-221402](https://github.com/yourselfhosted/slash/assets/50121594/b3b243ca-abc0-46f3-a433-d3e6411efd34)

![Screenshot_20240131-221715](https://github.com/yourselfhosted/slash/assets/50121594/d2688eed-0628-4c67-b92e-965cda87c385)

The .env content could look like this for instance, as mentioned in the screenshot above:

`root@pi4:~/docker-slash$ cat .env
DEFAULT_URL_VISIBILITY=private
root@pi4:~/docker-slash$ docker-compose restart`

**Comment by boojack** [comment]
Updated with https://github.com/yourselfhosted/slash/commit/4a6c6b4b2aaaf6d290f30555fc28592d73b37b30

<img width="1362" alt="image" src="https://github.com/yourselfhosted/slash/assets/24653555/70cfe237-9a69-4f15-8014-eb1add18b713">

**Comment by jon-f-novastor** [comment]
@boojack thank you, that screenshot of the change in the UI looks good!
