### ISSUE TITLE
Can I allow visitors to view my bookmarks without logging in?

### ISSUE THREAD

**Issue by Robert-Stackflow** [yourselfhosted/slash#64]
Slash is a great self-hosted bookmark manager, but I've found an issue where I can't seem to get a visitor to see the public bookmarks I've shared without logging in. Please tell me how to achieve this effect.

**Comment by boojack** [comment]
Create a [collection](https://github.com/yourselfhosted/slash/blob/main/docs/getting-started/collections.md), then select the shortcut you want to share, and share the link to the collection so others can see it. e.g. https://demo.slash.yourselfhosted.com/c/minecraft
