### ISSUE TITLE
All links go to 404 page

### ISSUE THREAD

**Issue by trevor68** [yourselfhosted/slash#66]
### Describe the bug

All of my public links only work if I am logged into slash. Once I log out, they all give 404 error page. 

### Steps to reproduce

1: create a public link
2: test it works fine
3: log out
4: now the same link goes to a 404 error page. 

### Expected behavior

Public links should be accessible to the public, aka my friends, without the need to be logged in. 

### Screenshots or additional context

![Screenshot 2024-02-06 225222](https://github.com/yourselfhosted/slash/assets/91324171/d9e30528-7df8-463d-ab66-30713db37de3)
![Screenshot 2024-02-06 225300](https://github.com/yourselfhosted/slash/assets/91324171/eaac2692-9045-42dc-88c8-fb6e0e5b56cc)

**Comment by boojack** [comment]
@trevor68 Thanks for the reporting, it'll be fixed with https://github.com/yourselfhosted/slash/commit/435fe04ab31b114efab70f79a6296d8e6b412870
