### ISSUE TITLE
Requset hash tag can be sorting

### ISSUE THREAD

**Issue by tarocjsu** [yourselfhosted/slash#67]
### Is your feature request related to a problem?

Requset hash tag can be sorting

### Describe the solution you'd like

Requset hash tag can be sorting

### Additional context

HashTagAskingSorted

**Comment by Zeo070** [comment]
Hello,thanks FOR the reply I am marketing expert and I would help you target the right people you need FOR your extension to grow and the people would be real user's people who would use your extension and give real and authentic feedback and not bot my percentage for this is 1$ per user/per review and with my classified campaign we can reach a large number of people that needs your extension
