### ISSUE TITLE
Ability to assign Tag or List to a new Bookmark in Chrome Extension

### ISSUE THREAD

**Issue by madcoda9000** [yourselfhosted/slash#69]
### Is your feature request related to a problem?

Everytime I've. created a new bookmark using the chrome extension, I've to go to the slash page, select the newly created bookmark, click on edit and assign a list or tag.

### Describe the solution you'd like

It would be awesome if the chrome extension would have the possibility to assign a list or tag on creation.

**Comment by boojack** [comment]
Updated with https://github.com/yourselfhosted/slash/commit/47821879fa466cfeace13293cdb0dc68aae8e21d
