### ISSUE TITLE
Supports API calls to generate short links

### ISSUE THREAD

**Issue by IllTamer** [yourselfhosted/slash#72]
### Is your feature request related to a problem?

-

### Describe the solution you'd like

1. Open API interface (access based on token)
2. Allow setting short links through API, including setting default access permissions
3. Optional: Support more short link types, such as expired short links, and support automatic generation of unique access IDs

**Comment by boojack** [comment]
You can create a shortcut by calling API. The short url can be specified in request body.
https://github.com/yourselfhosted/slash/blob/main/proto/gen/apidocs.swagger.md#post-5
