### ISSUE TITLE
Export to csv

### ISSUE THREAD

**Issue by N1jos** [yourselfhosted/slash#73]
### Is your feature request related to a problem?

An export to csv for links would be nice.

### Describe the solution you'd like

One export button in the settings screen for all links and maybe one on each collection.

**Comment by boojack** [comment]
Hi, before start, I'd like to what the usage scenarios are. I was thinking that you could use the API to get the data and then export it to whatever format you want.

**Comment by N1jos** [comment]
Mainly for when you don't have access to your data that you can get a useful csv from it.
Or if you want to share a collection with someone but your slash instance is not open to the public internet.

but the api looks promising - thanks!

**Comment by michaelien** [comment]
See more in the API docs: https://github.com/yourselfhosted/slash/blob/main/proto/gen/apidocs.swagger.md#apiv1shortcuts
