### ISSUE TITLE
Default to public in Chrome Extension

### ISSUE THREAD

**Issue by Narrron** [yourselfhosted/slash#78]
### Is your feature request related to a problem?

在 Chrome 拓展中也应该可以设置为新增的链接是 public 属性

### Describe the solution you'd like

可以在拓展中直接配置，由用户自定义默认添加的是 public 还是 private。现在的是 private

**Comment by boojack** [comment]
Updated with https://github.com/yourselfhosted/slash/commit/e2c7b8c7b9ff6de128912f53a5bec2fb42ab8739
